language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project

    # The SDK version used to compile your project

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests

before_script:
  - yes | sdkmanager "platforms;android-30" "build-tools;30.0.2"
script:
  - ./gradlew build

branches:
  only:
    - 'alexandre'
